### ISSUE TITLE
Delay on close tab button

### ISSUE THREAD

**Issue by alirgion** [ranmaru22/firefox-vertical-tabs#114]
Hi, 
I wanted to ask if it's possible to put a delay on the close tab button. I keep hitting it and closing the tab instead of switching to it.
Thanks for any help in advance

**Comment by ranmaru22** [comment]
Should be possible by setting the opacity to 0 and visibility to hidden, and then putting a transition on it that has a short delay.

I am struggling with the idea of introducing this as a default though, because the CSS is getting huge as it is and I really don't see much benefit in this. Feel free to add it as a personal mod, though.
