### ISSUE TITLE
Any way to remove the close button and increase favicons size?

### ISSUE THREAD

**Issue by lucfig** [ranmaru22/firefox-vertical-tabs#115]
Exactly as the title says. I am using Firefox as a Rambox replacement. I've set the sidebar to never expand and am using it only for web apps such as whatsapp and telegram.

I found that I can add the following to userchrome, but it only removes the close button of the regular firefox tabbar, not the sidebar one:
`@namespace url("http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul");
.tab-close-button { display: none !important; }`

**Comment by ranmaru22** [comment]
Yes, this is possible via CSS. However, I will not make this a default option because that's clearly not the point of this mod, which is to emulate an Edge-like implementation of a tab sidebar.

I think an extension like [Sideberry](https://addons.mozilla.org/en-US/firefox/addon/sidebery/) would suit your needs better.
