### ISSUE TITLE
1440p issue?

### ISSUE THREAD

**Issue by sobear69** [ranmaru22/firefox-vertical-tabs#137]
Hello,

I just started using this wonderful addon but I'm having issues with the size of the tab bar as you can see on the screenshot.

![2023-10-18_20-37](https://github.com/ranmaru22/firefox-vertical-tabs/assets/107318832/863f19f0-70e7-428e-8f5d-2d14ed6572c0)

Any ideas how to fix it and preferably disable the 'Filter tabs' thingie?

**Comment by ranmaru22** [comment]
I'm like 90% sure this is because of the payload size issue. This is what it looks like when the TCR style isn't applied. 

Did you use the minified version of tabCenterReborn.css as mentioned in the Readme? If not, you need to manually delete all the styles you don't use from that file, otherwise it's too large and Firefox won't load it.

**Comment by sobear69** [comment]
My apologies, that was it. Just importing tabCenterReborn.css fixed the issue.
