### ISSUE TITLE
Tab Bar Overlaps Search Box Suggestions After Clicking "New Tab"

### ISSUE THREAD

**Issue by theamazing0** [ranmaru22/firefox-vertical-tabs#22]
## Steps To Reproduce
1. Hover Over The Tab Bar
2. Click The New Tab Button
3. Do Not Move The Mouse, Firefox Will Automatically Refocus The Cursor To The Search Box
4. Start typing, the search box suggestions will be covered by the tab bar

Not sure but could this be fixed by adding an option to disable the "hiding functionality" and just show the tabs always.

![image](https://user-images.githubusercontent.com/66532288/159143249-1c6e258b-cc94-4f9c-99ca-e911ce0d2ff6.png)

**Comment by theamazing0** [comment]
Note: I was using the default firefox start page on contary to the DuckDuckGo website in the screenshots.

**Comment by ranmaru22** [comment]
To disable the auto-hide, you have to edit the CSS files. In userChrome.css it's the `#sidebar-box[sidebarcommand*="tabcenter"]` parts (there's width parameters which you can remove and then just get rid of all the `:hover` classes). That would make the sidebar behave like normal.

In tabCenterReborn.css you would also have to get rid of all the `:hover` stuff and then change the visibility of things that are hidden on non-hover, like the new tab button and the titles, back to visible.

It's not possible to do this via a setting, I am afraid, because the whole things works through CSS only.

I will take a look if I can fix this behaviour via z-index, though. I assume it's possible to just move the sidebar below the URL bar popup.

**Comment by theamazing0** [comment]
Thanks that worked well, looking perfect and very functional

**Comment by theamazing0** [comment]
It would be cool if this was included as a seperate "mode" or folder of css files in the repo. I would do it but I don't know how committing to public repos works.

**Comment by theamazing0** [comment]
however, the sidebar is still under the search suggestions box

(I just realized I'm pinging you with every comment, sorry)

**Comment by theamazing0** [comment]
Setting the z-index of `#sidebar-box[sidebarcommand*="tabcenter"]` to 1 fixes the problem.

**Comment by ranmaru22** [comment]
Thanks, I've tested and included it in the main branch. I will keep the issue open and flagged as enhancement for now for the "other mode" thing and consider adding this later.

**Comment by theamazing0** [comment]
i can format and clean up the configs for a seperate mode if you want, I've just never really used git so I have no idea how to commit to a public repo.

**Comment by ranmaru22** [comment]
If you have a working version, that would be much appreciated and I could get that in quickly. 😄 

Contributing is easy, there's two options:
1. Fork this repo, make your changes there, and then make a pull request against this repo. This is the usual way people do it on GitHub and doing that will get you listed as a contributor on the project. [See here](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork).
2. Clone this repo, make your changes locally, and then use `git format-patch` to create a patch file and post that here.

**Comment by ranmaru22** [comment]
I realized there was another issue with this. The `#urlbar` itself also needed a z-index for this to work properly. Should now finally be completely fixed with #26.
