### ISSUE TITLE
Missing the close, minimize and maximize buttons

### ISSUE THREAD

**Issue by happiestplants** [ranmaru22/firefox-vertical-tabs#33]
I don't know if anyone is experiencing this as well but I can't use the exit and minimize buttons on the top left of my browser anymore. It wasn't working before the bug was fixed and it still isn't now either. I am using a custom theme which makes the buttons appear but when I disable the theme the buttons don't appear at all.

Thanks for the help!

**Comment by ranmaru22** [comment]
Which operating system are you using? The window decorations work different depending on that, and in Linux, it can even vary depending on the GTK theme you use (as some will have the buttons right, some left, and some not at all).

I primarily use macOS, where the button placement is comparably easy because Apple's HIG are very strict about how things have to work, and Linux with tiling WMs, which don't show buttons at all, so that's what the mod is optimized for. 

I would suggest playing around with the `.titlebar-*` sections in `userChrome.css`. Those modify how that works, and by tweaking them, you can make it look perfect for your setup.

**Comment by happiestplants** [comment]
I am indeed using windows. The thing is, when I disable the theme, I don't have any of the buttons show up at all. It's only with the theme enable that I have nonfunctional buttons.
![image](https://user-images.githubusercontent.com/19482287/177010561-9f1d84a0-1458-46f8-b11a-309051f1fe41.png)
Here's a screenshot of my browser without the theme enabled. The buttons that should be on the top right have disappeared.

**Comment by ranmaru22** [comment]
Oh, could it be that this theme expects you to use the OS window decorations?

This is basically a setting that offloads handling of the close/maximize buttons to the OS's window manager.

Try setting the value of `browser.tabs.drawInTitlebar` in `about:config` to false and see if that does anything.

**Comment by happiestplants** [comment]
It didn't do anything. Just to be clear, I am not using the theme while trying to troubleshoot this. Everything was working before the past Firefox update that broke the CSS :(

**Comment by ranmaru22** [comment]
In that case this seems to be a Windows-specific issue because the update didn't break anything for me on macOS or Linux. 

Since I can't support Windows myself, I'll flag this as a bug with help wanted, hoping someone can figure it out and provide a fix.

**Comment by happiestplants** [comment]
Update: The solution linked in Issue #34 fixed it for me. The fix is removing ```#nav-bar, #urlbar { z-index: 100; }``` from userChrome.css
