### ISSUE TITLE
Greyish tint and invisible white favicons

### ISSUE THREAD

**Issue by bphd** [ranmaru22/firefox-vertical-tabs#43]
Is there an opacity parameter to set?
Is there an option to create a black/white border to the fav-icons? Because it seems like the page have no fav-icon at all when it's white on white/black on black

**Comment by bphd** [comment]
(Is it possible to widen the tab space, to see more of the title? Ideally even a grab to widen with mouse the menu width)

**Comment by ranmaru22** [comment]
You can give a background color to the favicon container, sure. I won't put this into the code as a default
option though because it's not the theme's (or browser's) responsibility. The colors of the sidebar are almost the same as the background colors of the normal tabs, which is intentional, so that it does not look too different. 

Any favicon that isn't visible in the sidebar will almost guaranteed also not be visible in Firefox's normal tab bar. 

As for the width of the expanded sidebar, that's set in the `#sidebar-box[sidebarcommand*="tabcenter"]:hover` selector. `width` is how wide it should be (currently at 30% of the window size) and `max-width` is the cap (currently 200px). You probably want to change the `max-width`.

**Comment by bphd** [comment]
#sidebar-box[sidebarcommand*="tabcenter"]:hover #sidebar,
#sidebar-box[sidebarcommand*="tabcenter"]:hover {
    min-width: 10vw !important;
    width: 30vw !important;
    max-width: 200px !important;
    z-index: 10 !important;
    transition: all var(--transition-time) ease var(--delay);
}

to

#sidebar-box[sidebarcommand*="tabcenter"]:hover #sidebar,
#sidebar-box[sidebarcommand*="tabcenter"]:hover {
    min-width: 10vw !important;
    width: 30vw !important;
    max-width: 400px !important;
    z-index: 10 !important;
    transition: all var(--transition-time) ease var(--delay);
}

and restarted, and it's the same

**Comment by bphd** [comment]
How to move multiple tabs from a window to another?

**Comment by ranmaru22** [comment]
This depends on the window size obviously. If 30vw is reached and is below the `max-width`, you have to change this as well. 

As for moving multiple tabs at one: not possible. And this has nothing to do with this theme. Not possible in Firefox generally. You can only drag and drop one tab at a time.

**Comment by bphd** [comment]
Try by yourself

Take a fresh profile of vanilla Firefox, open two windows, three tabs, select one tab, hold Control while selecting the second tab, and drag to the second window. You should now have three tabs in one window

**Comment by ranmaru22** [comment]
I see. I didn't know this. 

But please realize that this is not a browser plug-in. It's a CSS tweak. It's very much impossible to replicate the full feature set of the normal tab bar because we're relying on a completely different API here (sidebar, and then on Tab Center Reborn as an intermediary). 

I am afraid this isn't something we can implement unless Firefox decides to support this natively.

**Comment by bphd** [comment]
I say plug in because the functionality remains in the plugin, not your theme. Some CSS cannot change how tabs are moved

**Comment by bphd** [comment]
#sidebar-box[sidebarcommand*="tabcenter"]:hover #sidebar,
#sidebar-box[sidebarcommand*="tabcenter"]:hover {
    min-width: 10vw !important;
    width: 50vw !important;
    max-width: 400px !important;
    z-index: 10 !important;
    transition: all var(--transition-time) ease var(--delay);
}

And it remains the same, and it's faaaar from taking 50% of the space. It still takes exactly 250 pixels, like before any modification
Maybe another parameter comes into play

**Comment by bphd** [comment]
Greyish tabs seems to be unloaded tab, so I think it's expected (although it stills unreadable)

Maybe following upstream to Mozilla the color problem about favicons and unactive tab colors
