### ISSUE TITLE
Tab Center Reborn shows white space when items overflow

### ISSUE THREAD

**Issue by Rinto-kun** [ranmaru22/firefox-vertical-tabs#75]
If possible, I would like to remove the jarring whitespace on top and bottom that appears when number of tabs overflows. Any suggestions?

Version: 106.0.3 (Windows - happens on MacOS and Ubuntu too)
![image](https://user-images.githubusercontent.com/17642766/199593196-4e9e83ec-8f1f-4e1b-8d8d-c75ca154ee1a.png)

**Comment by ranmaru22** [comment]
I restyled this in the latest version with a little triangle instead of this shadow effect. It looks OK but not great, in my opinion, especially when you have pinned tabs above it because those will be above the indicator.

![image](https://user-images.githubusercontent.com/16521734/199690359-b485551d-5b2d-40cf-ac69-f2a628c530da.png)

![image](https://user-images.githubusercontent.com/16521734/199690217-1736cf2d-f95a-4370-b035-2b70970367df.png)

If anyone has a better-looking solution, I'm open for suggestions. The selectors for this are `#topshadow` and `#bottomshadow` in `tabCenterReborn.css`.

**Comment by Rinto-kun** [comment]
The bottom arrow doesn't hide when scrolled to the bottom. (Not sure how to solve this)

I do like the arrow approach but they either look awkward without enough space.

Here's a simple patch from me to add more space.
![image](https://user-images.githubusercontent.com/17642766/199850716-46e0ab54-1938-4e19-9c70-beac538283b5.png)

![image](https://user-images.githubusercontent.com/17642766/199850852-dde8cc19-ddce-4c09-bf26-28f55aafb24c.png)

With pins:
![image](https://user-images.githubusercontent.com/17642766/199851069-fa5fe81c-196a-49e8-b250-76677a847185.png)

Problem is, it may feel like it's occupying a bit more space for users without overflowing tabs. (also, the issue with the non-disappearing bottom arrow persists)

`
#topshadow, #bottomshadow {
    box-shadow: none;
    border: 1px solid transparent;
    padding: 10px 10px;
}
#topshadow::after {
    top: 8px;
    transform: translateX(-50%) rotate(-135deg);
}

#bottomshadow::after {
    bottom: 8px;
    transform: translateX(-50%) rotate(45deg);
}`

**Comment by ranmaru22** [comment]
I tried adding space there too but I really didn't like that it reserved that space even when no tabs overflowed. I will try around some other things and see if I can find away to only do that when it's necessary.

The problem with the non-disappearing bottom arrow is one I can't reproduce by the way. It works fine here (macOS & Linux).

**Comment by Rinto-kun** [comment]
Tbh after getting used to it, I don't mind the reserved space too much.

The arrow disappears on MacOS but not on Windows for me.

**Comment by ranmaru22** [comment]
@Freeplayg's solution works nicely, in my opinion. Much better than what I've come up with. I consider this solved then. ;)
