### ISSUE TITLE
Latest Firefox update problem

### ISSUE THREAD

**Issue by DaitiDay** [ranmaru22/firefox-vertical-tabs#77]
With the latest firefox update (107.0) the sidebar does not get resized by the css and covers part of the underlying page. I tried to solve the problem on my own but I couldn't do it :( It looks like something that can be fixed by a change in the css imo.
![immagine](https://user-images.githubusercontent.com/58434456/202114033-4758c95b-c3a4-4f0a-bced-82aa78148cab.png)

**Comment by ranmaru22** [comment]
<sigh> ... this has been happening for every single update recently and it's really annoying.

I'll take a look at it later tonight.

**Comment by DaitiDay** [comment]
Thank you!

**Comment by ranmaru22** [comment]
107 should be supported out of the box. The current release of the mod is build with 107. I was confused because I thought this was happening on 108 again. :D

Anyway, this issue was there before and has since been fixed with release 5.5 specifically (the PR for this was #73). Can you confirm that you have the version where this fix is included? It seems really strange, because I can't reproduce this.

**Comment by DaitiDay** [comment]
I'm sooo dumb. I've updated the extension's css twice and not the userChrome.css. Everything is working fine. Sorry for the inconvenience.
