### ISSUE TITLE
Page get truncated at left in fullscreen

### ISSUE THREAD

**Issue by outloudvi** [ranmaru22/firefox-vertical-tabs#78]
Case on Firefox Nightly 109.0a1 (2022-11-15), Arch Linux:

![image](https://user-images.githubusercontent.com/19144373/202202792-6a031320-f639-4117-8b8d-4ebef914fc39.png)

**Comment by ranmaru22** [comment]
That's strange. This issue has been reported before and had been addressed. I can't reproduce this on 107. 

Please ensure that you're on the current version and that your userChrome.css as well as the TCR CSS is up to date.

**Comment by ranmaru22** [comment]
Ah, sorry, I misunderstood this issue. Yes, this is in fact expected behavior. In full screen mode the sidebar is hidden and can be shown by moving the cursor to the side in the same fashion as the normal tab bar behaves.

**Comment by bmFtZQ** [comment]
This was caused by my solution to #70. Adding the `!important` flag caused the max-width value of the sidebar to be set to 48px, and overwriting the fullscreen rules. I've made a pull request that fixes this.

I also added an easy way to disable the fullscreen functionality by setting `--fullscreen-sidebar-width` to `48px` inside `userChrome.css`. This will cause the sidebar to have the same collapsed width in fullscreen mode as it does in windowed mode.
